name: Bump version after release

on:
  workflow_dispatch:
  workflow_call:

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        run: python3 .github/workflows/bump-version/bump-version.py

      - name: Check if there are changes
        run: |
          git diff --exit-code || touch git_diff_exists
          if [ -f git_diff_exists ]; then echo "Changes need to be commited"; else echo "No changes to commit"; fi

      - name: Commit package.json
        if: hashFiles('git_diff_exists') != ''
        run: |
          git config user.name 'GitHub'
          git config user.email '<noreply@github.com>'
          git add package.json
          git commit -F commit_message.txt || echo "package.json is not changed"

      - id: commit-message-from-file
        name: Parse commit message from file into variable
        if: hashFiles('git_diff_exists') != ''
        run: |
          body=$(cat commit_message.txt)
          body="${body//$'\n'/'%0A'}"
          echo ::set-output name=body::$body

      - name: Create Pull Request
        if: hashFiles('git_diff_exists') != ''
        uses: peter-evans/create-pull-request@v6
        with:
          title: Version bump after release
          body: ${{ steps.commit-message-from-file.outputs.body }}
          reviewers: |
            olehermanse
          branch: version-bump
          base: ${{ github.head_ref }}
