# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM release workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  bump-version:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Bump version
        run: python3 .github/workflows/bump-version.py

      - name: Check if there are changes
        run: |
          git diff --exit-code || touch git_diff_exists
          if [ -f git_diff_exists ]; then echo "Changes need to be commited"; else echo "No changes to commit"; fi

      - name: Commit and push
        if: hashFiles('git_diff_exists') != ''
        run: |
          git config user.name 'GitHub'
          git config user.email '<noreply@github.com>'
          git add package.json
          git commit -F commit_message.txt || echo "package.json is not changed"
          git reset --hard HEAD
          git push origin HEAD:main
